MODULE tpScanner;

  CONST
    (* nouns, գոյականներ *)
    nAkesi*       = 0;
    nAla*         = 1; (* nothing *)

    (* verbs, բայեր *)
    alasa*        = 100;

    (* adverbs, մակբայեր *)

    (* adjectives, ածականներ *)
    adjAla*       = 300; (* no, none *)
    adjAle*       = 301;
    adjAnpa*      = 302;

    (* interjections, ձայնարկութիւննե՞ր *)
    interjA*      = 400;
    interjAla*    = 401; (* no! *)
    
END tpScanner.
